SRCS =	main.cpp HumanA.cpp HumanB.cpp Weapon.cpp

OBJS =	${SRCS:.cpp=.o}

NAME =	main

RM =	rm -f

CC =	c++

FLAGS =	-Wall -Wextra -Werror -std=c++98

%.o: %.cpp
	${CC} ${FLAGS} -c $< -o $@

${NAME}: ${OBJS} HumanA.h HumanB.h Weapon.h
		 ${CC} -o ${NAME} ${OBJS} ${FLAGS}

all: ${NAME}

clean:
		${RM} ${OBJS}

fclean: clean
		${RM} ${NAME}

re: fclean all

.PHONY: all clean fclean re